{% set name = "vacuum" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v{{ version }}.tar.gz
  sha256: 51d9fe0a91174e3a5450b8a8b6aa7b027453a47b84c069209ae3a2f3b455e89d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - vacuum --help

about:
  home: https://github.com/daveshanley/vacuum
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  dev_url: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
