{% set name = "vacuum" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v{{ version }}.tar.gz
  sha256: 3af2251e31bc499cbd992bb7060e5e91e82d73f4935fd5b30c0eac18e4c54a98

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - vacuum --help

about:
  home: https://github.com/daveshanley/vacuum
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  dev_url: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
