{% set name = "vacuum" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v{{ version }}.tar.gz
  sha256: 5c004140fdd4c3585fce99f719311a7edb80502107d4a75c306acc348e97479b

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - vacuum --help

about:
  home: https://github.com/daveshanley/vacuum
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  dev_url: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
