context:
  version: "0.25.6"

package:
  name: vacuum
  version: ${{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v${{ version }}.tar.gz
  sha256: 0eebdb7b96c534c14f21495f3f0c505341a34f88805c58c234c75c1dba9afa93

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vacuum --help

about:
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  homepage: https://github.com/daveshanley/vacuum
  repository: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
