context:
  version: "0.21.4"

package:
  name: vacuum
  version: ${{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v${{ version }}.tar.gz
  sha256: fd41c8feaa00e33c37220c335425b68f609cf39781c8e1d7ee88e6b07a8a0185

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vacuum --help

about:
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  homepage: https://github.com/daveshanley/vacuum
  repository: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
