context:
  version: "0.26.7"

package:
  name: vacuum
  version: ${{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v${{ version }}.tar.gz
  sha256: b2fda08bcd1d1d19a716c2e29a2cb0d85ddcfd45c0562c4ad5d4363090e143dc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vacuum --help

about:
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  homepage: https://github.com/daveshanley/vacuum
  repository: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
