context:
  version: "0.19.5"

package:
  name: vacuum
  version: ${{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v${{ version }}.tar.gz
  sha256: f6bd4c1ef9c4ac23691b14ba896543f5acca0785b409a72b5deab2293157e858

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vacuum --help

about:
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  homepage: https://github.com/daveshanley/vacuum
  repository: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
