context:
  version: "0.24.0"

package:
  name: vacuum
  version: ${{ version }}

source:
  url: https://github.com/daveshanley/vacuum/archive/v${{ version }}.tar.gz
  sha256: d8943b543c22e13ed4fa30c783757c23cea4c9890a8e14c0790aea1cc9144855

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vacuum --help

about:
  license: MIT and BUSL-1.1
  license_file:
    - LICENSE
    - license-files/
  summary: vacuum is the worlds fastest OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
  homepage: https://github.com/daveshanley/vacuum
  repository: https://github.com/daveshanley/vacuum

extra:
  recipe-maintainers:
    - danielnachun
